src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 255)]
    private $description;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 255)]
    private $description;

    #[ORM\Column(type: 'string', length: 255)]
    private $image;

    #[ORM\Column(type: 'integer')]
    private $category_id;

    /**
     * @return mixed
     */
    public function getCategoryId()
    {
        return $this->category_id;
    }

    /**
     * @param mixed $category_id
     */
    public function setCategoryId($category_id): void
    {
        $this->category_id = $category_id;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Manager\ProductManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProductController extends AbstractController
{
    private EntityManagerInterface $entityManager;
    private ProductManager $productManager;

    public function __construct(
        EntityManagerInterface $entityManager,
        ProductManager $productManager,
    )
    {
        $this->entityManager = $entityManager;
        $this->productManager = $productManager;
    }

    /**
     * @throws \Doctrine\DBAL\Exception
     */
    #[Route('/', name: 'product')]
    public function index(): Response
    {
        $result = $this->productManager->getProducts();

        return $this->render('product/index.html.twig', [
            'products' => $result['products'],
            'connected' => $result['connected']
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <title>{% block title %} Product Management App {% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
                  integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
                  crossorigin="anonymous">
            <link rel="stylesheet" href="{{ asset('css/page.css') }}"/>
        {% endblock %}
    </head>
    <body>

    {% block header %}
        {% include('includes/navbar.html.twig') %}
    {% endblock %}

        {% block body %}{% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </body>
</html>

templates/includes/navbar.html.twig
<nav class="navbar navbar-dark bg-primary sticky-top">
    <a href="#" class="navbar-brand">
        Product Management App
    </a>

    <div style="color: white; font-weight: bolder">
       <p> Welcome! </p>
    </div>
</nav>

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Products{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">

    {% if connected %}
        <div class="alert alert-success">
            <p>You are connected to <i> {{ connected }}</i></p>
        </div>
    {% else %}
        <div class="alert alert-danger">
            <p>Your database is not connected </p>
        </div>
    {% endif %}

    <div>
        <div>
            <h2>List of products</h2>
        </div>

        <div>
            <div class="container py-5">
                {% if products %}
                    <div class="row">
                        <div class="col-lg-12 mx-auto">
                            <ul class="list-group shadow">
                                {% for product in products %}
                                    <li class="list-group-item">
                                        <div class="media align-items-lg-center flex-column flex-lg-row p-3">
                                            <div class="media-body order-2 order-lg-1">
                                                <h5 class="mt-0 font-weight-bold mb-2">{{ product.name }}</h5>
                                                <p class="font-italic text-muted mb-0 small">{{ product.description }}</p>
                                                <p><small> Category: <b>{{ category(product.categoryId).name }}</b></small></p>
                                            </div>
                                            <img src="{{ product.image }}" alt="Generic placeholder image" width="250"
                                                 class="ml-lg-5 img-fluid order-1 order-lg-2">
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                {% else %}

                    <div class="row">
                        <p>No products found</p>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>


</div>
{% endblock %}